### PR TITLE
fixes #62

### LINKED ISSUE #62: Adding TopShelf Support
TopShelf support on the home screen of Apple TV to include showing;
- Watchlist
- Latest Movies
- Latest TV Shows

[Documentation](https://developer.apple.com/library/tvos/documentation/TVServices/Reference/TVTopShelfProvider_Ref/index.html#//apple_ref/doc/uid/TP40016416-CH1-DontLinkElementID_6) _Tried to implement myself before however didn't succeed_

### PR DESCRIPTION
**Pull request by tengis**
Implemented Latest Movies & Popular TV Shows. I hope this is pretty
much close that requirements. Thanks 😀

### CODE REVIEW

**Comment by tengis** [comment]
hmm very interesting. On my XCode ** import PopcornKit** working fine. Why this is did not passed? @buzzel

**Comment by RefusedFlow** [comment]
Adding this to the Podfile fixes this issue, awesome job on the top shelf! @tengis 

`target 'TopShelf' do
  pods
end`

**Comment by tengis** [comment]
@RefusedFlow tnx all passed now 💃

**Comment by buzzel** [comment]
In future @tengis make sure to give the title a bit more description of what the PR is. :)

**Comment by tengis** [comment]
@buzzel Yep no problem

**Pull request merged**
