### PR TITLE
Web server to host downloaded files.

### PR DESCRIPTION
**Pull request by smith288**
Rather than having the ability to connect to a Samba share and automagically copy the file over when the download is complete (still cool i think), I implemented this web server that will list out the files in the Downloads folders that is created when a torrent begins.  

It will allow for the browsing from a remote browser and download the media directly if you wish to archive them elsewhere.  It can be enabled via the settings and a new option that will start the server when the option it turned to Yes.

It's not the prettiest built in web service I've seen from a tvOS app but it does get the job done.

What do you think?

### CODE REVIEW

**Comment by buzzel** [comment]
Torrents stream to the cache folder, this is so if you restart your device or if the system needs more memory it can clear them out. I suggest having the web server point there instead of the downloads/documents folder. Also, make sure to `swiftlint` the project as well :)

**Comment by smith288** [comment]
So it does. Whoops. Haha. Point taken on that swiftlint.  Read the contributions file but boy does Xcode do a number on code.

**Comment by smith288** [comment]
Wait, the web server looks at the cache folder's Downloads folder.  Isn't that the same place you're talking about?  I merely create a Downloads folder in the case where the user hasn't started a torrent stream as of yet so I have a place for the web server to load from.  Unless I'm missing something?  Thanks!

**Comment by smith288** [comment]
simulator screen shot jun 5 2016 8 49 54 pm
simulator screen shot jun 5 2016 8 50 00 pm

**Comment by buzzel** [comment]
Oh I gotcha! I was miss reading the implementation. I'll have some time this afternoon so I'll check out the PR and double check it all works and then merge it in.

**Pull request merged**
