### PR TITLE
Fix subtitles sizes

### PR DESCRIPTION
**Pull request by garranhado**
Change subtitles font size for TV experience.
New sizes from Apple design guides.

Also fix default size and some reloadData on settings.

### CODE REVIEW

**Comment by tiferrei** [comment]
Olá @garranhado! Thank you for you Pull Request, the changes seem good, good idea on implementing the guidelines, but could you please just update from upstream? I'm getting some merge conflicts.

Obrigado,
Tiago

**Comment by garranhado** [comment]
Ok

**Comment by garranhado** [comment]
Updated!

**Comment by tiferrei** [comment]
Thank you @garranhado, hum why did you change the file permissions? Can yo please set them back to `644`? Thanks!

**Comment by tiferrei** [comment]
To make stuff easier you can just run: `find top/directory -type f -exec chmod 0644 '{}' \;` and `find top/directory -type d -exec chmod 0755 '{}' \;` be sure to replace `top/directory` with the directory for the PopcornTimeTV repo.

**Comment by garranhado** [comment]
Updated file permissions. Thanks for the commands, I'm not really git expert.
Hope sove problem.

**Comment by tiferrei** [comment]
Don't worry @garranhado git also messes my head sometimes, I actually have those commands saved because this also happens to me a lot 😄

**Comment by tiferrei** [comment]
Thanks again @garranhado!

**Pull request merged**
