### PR TITLE
Temporary fix for 503 response error

### PR DESCRIPTION
**Pull request by rimonhanna**
Removed cookies storage and changed the urls to match Android to keep getting cached content from cloudflare the scrapper is hosted somewhere else

### CODE REVIEW

**Comment by rimonhanna** [comment]
@ricardopereira Do you still want me to take it out of this PR?

**Comment by ricardopereira** [comment]
No, it's fine. Thanks

**Comment by gduranon** [comment]
It's not working from my side... shouldn't It point to Cloudflare?

**Review by angryDuck2 — COMMENTED** [review]
I do not see how this fix could pull content from a server returning a 503 error? Have you tested this?

**Comment by Midifreakz** [comment]
@angryduck I can confirm that this tempfix works on ATV. I've read that it is pulling from Cloudflare cache so maybe it's not a bad idea to implement this in the master release as a redundancy option?

**Comment by patriziomunzi** [comment]
+1 on merging this to master

**Comment by hopye** [comment]
I dont see code in this pr to change urls to cloud flare, the only i see is to fix the warning about the ui being called on background thread

**Pull request merged**
