### PR TITLE
Show all available subtitles for each language - sorted by similarity to the movie name

### PR DESCRIPTION
**Pull request by matanelgabsi**
Currently, the first subtitle is always selected, even if it isn't in sync with the movie itself... This shows all the available subtitles so the user can choose which subtitle to use, and order them by the similarity to the name of the video file (this depends on a PR to PopcornTorrent).

### CODE REVIEW

**Comment by matanelgabsi** [comment]
No idea why this fails CI, this seems like a problem with cocoapods

**Comment by CavalcanteLeo** [comment]
Great...

would be even better if everything were sorted, not only subtitle, but **gender**, **subtitles**, **language**(in preferences), etc..

Gender should be:
All movies or all shows,
then all gender categories sorted by name

**Comment by ghost** [comment]
Although we appreciate the work, this looks horrible. We have changed the way we grab subtitles - we are searching through a larger amount and ordering by user rating now. Fetching every single subtitle and presenting it to the user is overwhelming and confusing. Having the best subtitle automatically fetched and adjusting the delay values, which now range from ± 60 seconds, is much better UX, IMO. You, and anyone else who thinks this is better, are more than welcome to use this on your own fork, but we won't be merging this with master. 

Thanks anyway!

**Comment by matanelgabsi** [comment]
I really disagree.
Rating does not hange anything - there are a lot of different videos for each movie/show, every one not only has different delay, but some also get out of sync every commercial break, and the current situation makes you change the delay every 5 minutes, which make subtitles un-useable.
I currently prefer using other software in order for subtitle to work properly, the current situation is pretty shity.

But never mind, i'll just use it in my own fork

**Comment by jberglinds** [comment]
@FlaviaBondJamesBondsHusband UX is more than just UI. While I agree this may not be the best way to do it, you should definitely look over some options for it. The current implementation for subtitles is not very good, subtitles starting out of sync and getting out of sync every minute (which often has to do with editing by the uploader). The ±60 second is not very useful when the subtitles get out of sync that often, it could be improved by at least starting on the current value instead of -60.
It will however never be good enough if the core problem isn't tackled, which is choosing the correct subtitle from the start. Look how apps like Infuse or VLC allows it's users to select subtitles freely.

**Comment by ceuaugusto** [comment]
@matanelgabsi Hey! Do you have a PopcornTime TV version that you can choose the subtitle you want to best match the movie video? I'm asking you this because you said that you were going to use in your own fork. I'm having too much trouble because of the problem you mentioned about the subtitle not syncing with the movie...

If you actually changed your app version to solve the problem like you said you would, could you send me you version so I can use that too?

Thanks in advance!

**Comment by ejklock** [comment]
@CavalcanteLeo como faria para utilizar legendas pt-br e não só pt?

**Comment by CavalcanteLeo** [comment]
@ejklock, baixa esse popcorn que esta atualizado:

https://github.com/Kinglilrowrow/PopcornTimeTV

e na classe [SubtitlesManager.swift, na linha 23](https://github.com/Kinglilrowrow/PopcornTimeTV/blob/4.2.0/PopcornKit/Managers/SubtitlesManager.swift#L23), o metodo "search"


troca todo metodo por isso:

```swift 

open func search(_ episode: Episode? = nil, imdbId: String? = nil, limit: String = "500", completion:@escaping ([Subtitle], NSError?) -> Void) {
        guard let token = token else {
            login() { error in
                guard error == nil else { completion([], error); return }
                self.search(episode, imdbId: imdbId, limit: limit, completion: completion)
            }
            return
        }
        var params = ["sublanguageid": "pb,pob,por,eng"]
        if let imdbId = imdbId {
            params["imdbid"] = imdbId.replacingOccurrences(of: "tt", with: "")
        } else if let episode = episode {
            params["query"] = episode.title
            params["season"] = String(episode.season)
            params["episode"] = String(episode.episode)
        }
        let limit = ["limit": limit]
        let queue = DispatchQueue(label: "com.popcorn-time.response.queue", attributes: DispatchQueue.Attributes.concurrent)
        self.manager.requestXMLRPC(OpenSubtitles.base, methodName: OpenSubtitles.search, parameters: [token, [params], limit], headers: OpenSubtitles.defaultHeaders).validate().responseXMLRPC(queue: queue) { response in
            guard
                let value = response.result.value,
                let status = value[0]["status"].string?.components(separatedBy: " ").first,
                let data = value[0]["data"].array,
                response.result.isSuccess && status == "200"
                else {
                    return DispatchQueue.main.async {
                        completion([], response.result.error as NSError?)
                    }
            }
            var subtitles = [Subtitle]()
            for info in data {
                guard
                    let subDownloadLink = info["SubDownloadLink"].string?.replacingOccurrences(of: ".gz", with: ""),
                    let ISO639 = info["ISO639"].string,
                    let localizedLanguageName = Locale.current.localizedString(forLanguageCode: ISO639)?.localizedCapitalized,
                    let rating = Double(info["SubRating"].string ?? "")
                    else {
                        continue
                }
                
                let subtitle = Subtitle(language: localizedLanguageName, link: subDownloadLink, ISO639: ISO639, rating: rating)
     
                subtitles.append(subtitle)
            }
            
            DispatchQueue.main.async(execute: { completion(subtitles, nil) })
        }
    }
```
  

ele vai pegar todas as legendas em portugues brasil, portugues portugal e ingles

**Comment by ceuaugusto** [comment]
@CavalcanteLeo cara, nesse outro Popcorn que você colocou o link existe a opção de escolher legendas alternativas como o dono desse tópico falou e que você também sugeriu? Obrigado pela atenção!

**Pull request closed without merging**
