### PR TITLE
App icons

### PR DESCRIPTION
**Pull request by williamoconnorme**
Changes tvOS app icon to be consistent with iOS app icon.
Adds top shelf image to tvOS app
Update image in readme

### CODE REVIEW

**Comment by FuzzyNutz** [comment]
You can do it your self  in Xcode just add the new .png in the layer 1 folder and replace it in xcode if u have photoshop or sketchbook pro just use the color from the iOS icon and use the  character from tvOS layer 2


img_0972

**Comment by moh0sw1** [comment]
@FuzzyNuts 😂😂😂😂😂😂
@williamoconnorme is pushing a PR to change the official icon for the app he is not asking how to change it 😂😂😂

**Comment by FuzzyNutz** [comment]
And..... boom! Looks nice doesn't it ;), btw by any means I'm no expert so if I can do it so can you.

img_0973

**Comment by FuzzyNutz** [comment]
@moh0sw1 ummm I know that lol I'm just saying it's easy to do so if people want the icon changed they can do it them selves it's easy 👌🏼😝

**Comment by williamoconnorme** [comment]
@FuzzyNutz Yes it's very easy to change that app icon. Just be sure to follow the [
tvOS Human Interface Guidelines](https://developer.apple.com/tvos/human-interface-guidelines/icons-and-images/) and break the app icon into at least two layers so the parallax effect can be achieved.

**Comment by RefusedFlow** [comment]
Already have plans to redo the tvOS application icon, so this PR will be closed sorry
#390

**Pull request closed without merging**
