### PR TITLE
Add support for Kickass Search

### PR DESCRIPTION
**Pull request by aggelos81**
This adds the ability to directly search Kickass.

### CODE REVIEW

**Comment by buzzel** [comment]
Just quickly checking out this branch, it appears that it is quite outdated. I noticed an old PR you sent in regarding the Polish subtitle encoding. Can you make sure that your branch is up to date then apply your KAT commits on top of that. 

Can you also attach a few screenshots demonstrating your PR?

Also, the build seems to fail with this error 
`❌  /Users/travis/build/PopcornTimeTV/PopcornTimeTV/PopcornTime/Movie+Lockup.swift:23:11: use of undeclared type 'KATResult'
extension KATResult {
          ^~~~~~~~~
** BUILD FAILED **
`

**Comment by aggelos81** [comment]
The failure seems to be because this pr requires a pr made on popcorn kit! Also this branch is up to date, It just seems that the commits appear in reverse order!
Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=ti&cv=7.12.25&pv=9.3.2&source=email_footer_2]
On Fri, Jun 17, 2016 at 11:32 PM, buzzel <notifications@github.com> wrote:
Just quickly checking out this branch, it appears that it is quite outdated. I noticed an old PR you sent in regarding the Polish subtitle encoding. Can you make sure that your branch is up to date then apply your KAT commits on top of that.

Can you also attach a few screenshots demonstrating your PR?

Also, the build seems to fail with this error
❌ /Users/travis/build/PopcornTimeTV/PopcornTimeTV/PopcornTime/Movie+Lockup.swift:23:11: use of undeclared type 'KATResult'
extension KATResult {
^~~~~~~~~
** BUILD FAILED **

**Comment by aggelos81** [comment]
Also here are some screens of the functionality

simulator screen shot 18 jun 2016 00 04 28
simulator screen shot 18 jun 2016 00 04 45
simulator screen shot 18 jun 2016 00 04 52
simulator screen shot 18 jun 2016 00 05 08

**Comment by simonepsp** [comment]
Thanks aggelos81, this functionality is really appreciated.
Unfortunately I wasn't able to build it as I got the same error:

```
.../PopcornTimeTV/PopcornTime/Movie+Lockup.swift:23:11: use of undeclared type 'KATResult'
```

Furthermore:

-  I think would be better to load "kickass search" image element from local resources instead of downloading it from an image hoster (I'm refering to /Recipes/WelcomeRecipe.xml)

-  The project identifiers (such as PRODUCT_BUNDLE_IDENTIFIER) should remain set to com.popcorntime.PopcornTime[...] not to your username :)


I'm not a developer of the project so please take these considerations as suggestions :)
Thanks for your contribution.

**Comment by RefusedFlow** [comment]
@simonepsp tvOS doesn't allow you to store images and or video on the device permanently, they can be deleted whenever the system feels like it. So we're storing images on an external image sharing website, this might've changed in tvOS 10 but this haven't been looked into yet.

You're also getting an error because there's a PR on the PopcornKit branch, that handles the network activity for the implementation of Kickass Search that needs to be downloaded and added

**Comment by simonepsp** [comment]
@RefusedFlow thanks for pointing me out the problem.
I have edited the PodFile to clone PopcornKit from the aggelos81 repository.

> pod 'PopcornKit', :git => 'https://github.com/aggelos81/PopcornKit'

Compilation completed without errors :)

P.S. I didn't know that tvOS doesn't allow to store images. I hope that Apple will change idea about this.

**Comment by buzzel** [comment]
@RefusedFlow I dont have much time these days to sit down and do much for this project, but could you give this a test and double check that it work? I checked the PR on PopcornKit and it does look good there. Just want to make sure the app works. 

@aggelos81  Commit 1eec78d in your PR is what I was referring to. Merging this branch in will use that in place of the new changes.

**Comment by aggelos81** [comment]
Also there is something even bigger coming(hint: ff)

**Comment by Evhelden** [comment]
Tell us more?

**Comment by RefusedFlow** [comment]
@buzzel Tested out seems to be working fine! Has one small issue where the KickAss Domain is actually blocked by ISP where I'm from so I had to change it to kat.al. Everything works it's just it needs updating to the latest commit on the master branch as it's a few behind.

**Comment by aggelos81** [comment]
Could someone explain how to get my branch up to speed with this repo's master? Because I think I have with commit https://github.com/PopcornTimeTV/PopcornTimeTV/pull/173/commits/f843243d669733412b575b938cdfbd0c664665cc

**Comment by RefusedFlow** [comment]
@aggelos81 If you wouldn't mind changing the bundle id back to `com.popcorntime.PopcornTime`
I'd be more than happy to merge your PR to that master branch 😄

**Comment by aggelos81** [comment]
@RefusedFlow all done!

**Comment by aggelos81** [comment]
@RefusedFlow how can I send you something to try out? ff related ;)

**Comment by RefusedFlow** [comment]
@aggelos81 Absolutely, are you on the Slack group?
 http://popcorntimetv.herokuapp.com/

**Comment by aggelos81** [comment]
Nope

**Comment by RefusedFlow** [comment]
Join slack, and i'll invite you to the development channel? It's much easier to communicate & share files?

**Comment by aggelos81** [comment]
Alright just joined slack, username aggelos81

**Pull request merged**
