### PR TITLE
Fix of few crash when loading a product view by replacing or removing special characters from slug

### PR DESCRIPTION
**Pull request by TheAbstractDev**

### CODE REVIEW

**Comment by tiferrei** [comment]
Thanks @TheAbstractDev! 👍

**Comment by TheAbstractDev** [comment]
Your welcome 👍

**Comment by joaomvfsantos** [comment]
@TheAbstractDev @tiferrei Shouldn't we move the String extension to the String+Cleaned.swift file? Makes more sense to add this to this extension file than to add this loosly in ActionHandler.swift

**Comment by TheAbstractDev** [comment]
@joaomvfsantos Oh yes, I'm gonna do it

**Pull request merged**
