### PR TITLE
Update for iOS 12

### PR DESCRIPTION
**Pull request by MatthieuLab**
Update error on enum State  -> enum downloadButtonState
Update Metadata Management to conform to iOS 12
Update Media+Extension due to selectingTorrentBlock is not a parameter anymore

### CODE REVIEW

**Comment by MatthieuLab** [comment]
Please Review. 2 main corrections:

- App won't crash when menu displayed during player is on
- Avoid metadata management problem during compilation (TVOS 12)

Cheers,
Matthieu

**Comment by darkobg79** [comment]
THANK YOUUUUUUUUUUU! 

BIG Thank you... Now Popcorn on TVOS 12 work perfectly.

Issues #700 , #691 and #672 is resolved.

**Comment by galooper** [comment]
can you compile the app whit this corrections, thanks !!!

**Comment by andre79sa** [comment]
Yes... please compile the app with corrections for download

**Comment by darkobg79** [comment]
Compiled app for TVOS 12, problem with scrolling down top menu is resolved. Thank you @MatthieuLab 

Download and install a modified version that solves this problem from here: https://uptobox.com/2qp5jt6fn076 

It need to resign app.

**Pull request closed without merging**
