### PR TITLE
Resolved the crash in tvOS 11.4 when swiping down

### PR DESCRIPTION
**Pull request by xandervr**

### CODE REVIEW

**Comment by CavalcanteLeo** [comment]
please, accept this

**Comment by xandervr** [comment]
@CavalcanteLeo You can build my fork from source in the meantime...

**Comment by CavalcanteLeo** [comment]
I will as soon as i get home, i just saw the diff

**Comment by popcornMaster** [comment]
Thank you very much for your contribution, much appreciated. Pull merged

**Pull request merged**
